export class TeamUserInfoModel {
    clip_Count: number = 0;
    clip_Space: number = 0;
    dateCreated: string = "";
    doc_Count: number = 0;
    doc_Space: number = 0;
    filmExpires: string = "";
    filmStatus: string = "";
    film_Count: number = 0;
    isFilm: number = 0;
    isRoku: number = 0;
    ownerEmail: string = "";
    ownerName: string = "";
    photo_Count: number = 0;
    photo_Space: number = 0;
    rokuChannel: string = "";
    rokuExpires: string = ""
    rokuId: number = 0;
    rokuSatus: string = "";
    teamColor: string = "";
    teamGuid: string = "";
    teamId: number = 0;
    teamLevel: string = ""
    teamName: string = ""
    teamRole: number = 0;
    teamSport: string = "";
    userId: number = 0;
    user_Count: number = 0;

};