//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagment.Database_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HostelRoom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HostelRoom()
        {
            this.User_Room_Bed = new HashSet<User_Room_Bed>();
            this.User_Rooms = new HashSet<User_Rooms>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public int Floor { get; set; }
        public int NoOfBeds { get; set; }
        public int RoomNo { get; set; }
        public decimal RoomChangres { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Room_Bed> User_Room_Bed { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Rooms> User_Rooms { get; set; }
    }
}
