//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagment.Database_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_RoomRequest
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int Budegt { get; set; }
        public bool IsRoomAssigned { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> CheckIn { get; set; }
        public Nullable<bool> CancelRequest { get; set; }
    
        public virtual User User { get; set; }
    }
}
